<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.edlink.id/api/v1.4/university/kelasPerMinggu');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"isDefault\":1}");

$headers = array();
$headers[] = 'X-Gid: 796134';
$headers[] = 'Authorization: Bearer e5079b17f96748dfd61d393db2e162c0e13ba10991f3448f02a9c00cf3e66f7e47fe881b4b36f155482ac5ac476aca184f402d7c43f22694bc28d6ce4b7604b3a';
$headers[] = 'Sec-Ch-Ua-Platform: \"Windows\"';
$headers[] = 'Referer: https://edlink.id/';
$headers[] = 'Sec-Ch-Ua: \"Google Chrome\";v=\"129\", \"Not=A?Brand\";v=\"8\", \"Chromium\";v=\"129\"';
$headers[] = 'Sec-Ch-Ua-Mobile: ?0';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36';
$headers[] = 'Accept: application/json, text/plain, */*';
$headers[] = 'Dnt: 1';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
echo $result;
curl_close($ch);
